version: "3"

services:
  database-db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=productionpassword
    ports:
      - "5432:5432"

  database:
    image: database
    build: ./database
    container_name: database
    environment:
      - FLASK_ENV=prod
      - DATABASE_URI=postgresql://postgres:productionpassword@database-db/postgres
    depends_on:
      - database-db
    volumes:
      - "./database:/code"
    expose:
      - "5001"
    ports:
      - "5001:5001"

  engine:
    image: engine
    build: ./engine
    container_name: engine
    environment:
      - FLASK_ENV=prod
    volumes:
      - "./engine:/code"
    expose:
      - "5000"
    ports:
      - "5000:5000"

  web-app:
    image: web-app
    build: ./web-app
    container_name: web-app
    volumes:
      - "./web-app:/code"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - web-app